### ISSUE TITLE
How to solve this problem

### ISSUE THREAD

**Issue by MashiroCl** [sir-ragna/noprint#2]
This program is run on ubuntu16.4.04,eclipse,I saw a similar question https://github.com/sir-ragna/noprint/issues/1 , and I modified the pom.xml as he did , but it still has this problem.

Exception in thread "main" java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider
	at com.arxanfintech.sdk.wallet.Wallet.<init>(Wallet.java:48)
	at clclcl.upload.App.main(App.java:23)
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.jce.provider.BouncyCastleProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more

**Comment by sir-ragna** [comment]
I'm afraid I cannot help you. This is a dependency issue with your build environment.

This project is just a demo on how you could use the Apache Pdfbox library. I used it once to demonstrate a colleague on how he could use this library. (Note: I use the old pdfbox-app-1.8.7.jar version.) I have no intention of supporting it.
